package model;

import model.utilities.GeneralNutrientGroup;
import model.utilities.MU;
import model.utilities.NutrientGroup;

import javax.measure.unit.Unit;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by ${tomirodriguez} on 28/11/14.
 */
public enum Nutrient implements NutrientGroup {

    CALORIES(MU.CALORIE, GeneralNutrientGroup.ENERGY_INFORMATION),
    JULES(MU.JOULE, GeneralNutrientGroup.ENERGY_INFORMATION),

    // HIDRATOS
    CARBOHYDRATE(MU.GRAM, GeneralNutrientGroup.CARBOHYDRATES),
    FIBER(MU.GRAM, CARBOHYDRATE),
    STARCH(MU.GRAM, CARBOHYDRATE),
    // AZUCARES
    SUGARS(MU.GRAM, CARBOHYDRATE),
    SUCROSE(MU.GRAM, SUGARS),
    GLUCOSE(MU.GRAM, SUGARS),
    FRUCTOSE(MU.GRAM, SUGARS),
    LACTOSE(MU.GRAM, SUGARS),
    MALTOSE(MU.GRAM, SUGARS),
    GALACTOSE(MU.GRAM, SUGARS),

    //GRASA
    TOTAL_FAT(MU.GRAM, GeneralNutrientGroup.FAT_AND_FATTY_ACIDS),

    // SATURADAS
    SATURATED_FATS(MU.GRAM, TOTAL_FAT),
    _4_0(MU.GRAM, SATURATED_FATS),
    _6_0(MU.GRAM, SATURATED_FATS),
    _8_0(MU.GRAM, SATURATED_FATS),
    _10_0(MU.GRAM, SATURATED_FATS),
    _12_0(MU.GRAM, SATURATED_FATS),
    _13_0(MU.GRAM, SATURATED_FATS),
    _14_0(MU.GRAM, SATURATED_FATS),
    _15_0(MU.GRAM, SATURATED_FATS),
    _16_0(MU.GRAM, SATURATED_FATS),
    _17_0(MU.GRAM, SATURATED_FATS),
    _18_0(MU.GRAM, SATURATED_FATS),
    _20_0(MU.GRAM, SATURATED_FATS),
    _22_0(MU.GRAM, SATURATED_FATS),
    _24_0(MU.GRAM, SATURATED_FATS),

    // MONO
    MONOUNSATURATED_FAT(MU.GRAM, TOTAL_FAT),
    _14_1(MU.GRAM, MONOUNSATURATED_FAT),
    _15_1(MU.GRAM, MONOUNSATURATED_FAT),
    _16_1_C(MU.GRAM, MONOUNSATURATED_FAT),
    _16_1_T(MU.GRAM, MONOUNSATURATED_FAT),
    _16_1_U(MU.GRAM, MONOUNSATURATED_FAT),
    _17_1(MU.GRAM, MONOUNSATURATED_FAT),
    _18_1_C(MU.GRAM, MONOUNSATURATED_FAT),
    _18_1_T(MU.GRAM, MONOUNSATURATED_FAT),
    _18_1_T_N7(MU.GRAM, MONOUNSATURATED_FAT),
    _18_1_U(MU.GRAM, MONOUNSATURATED_FAT),
    _20_1(MU.GRAM, MONOUNSATURATED_FAT),
    _22_1_C(MU.GRAM, MONOUNSATURATED_FAT),
    _22_1_T(MU.GRAM, MONOUNSATURATED_FAT),
    _22_1_U(MU.GRAM, MONOUNSATURATED_FAT),
    _24_1_C(MU.GRAM, MONOUNSATURATED_FAT),


    // POLI
    POLYUNSATURATED_FAT(MU.GRAM, TOTAL_FAT),
    _18_2_I(MU.GRAM, POLYUNSATURATED_FAT),
    _18_2_N6_CC(MU.GRAM, POLYUNSATURATED_FAT),
    _18_2_T_T(MU.GRAM, POLYUNSATURATED_FAT),
    _18_2_CLAS(MU.GRAM, POLYUNSATURATED_FAT),
    _18_2_U(MU.GRAM, POLYUNSATURATED_FAT),
    _18_2_T_NFD(MU.GRAM, POLYUNSATURATED_FAT),
    _18_3_N3_CCC(MU.GRAM, POLYUNSATURATED_FAT),
    _18_3_N6_CCC(MU.GRAM, POLYUNSATURATED_FAT),
    _18_3_I(MU.GRAM, POLYUNSATURATED_FAT),
    _18_3_U(MU.GRAM, POLYUNSATURATED_FAT),
    _18_4(MU.GRAM, POLYUNSATURATED_FAT),
    _20_2_N6_CC(MU.GRAM, POLYUNSATURATED_FAT),
    _20_3_N3(MU.GRAM, POLYUNSATURATED_FAT),
    _20_3_N6(MU.GRAM, POLYUNSATURATED_FAT),
    _20_3_U(MU.GRAM, POLYUNSATURATED_FAT),
    _20_4_N6(MU.GRAM, POLYUNSATURATED_FAT),
    _20_4_U(MU.GRAM, POLYUNSATURATED_FAT),
    _20_5_N3(MU.GRAM, POLYUNSATURATED_FAT),
    _21_5(MU.GRAM, POLYUNSATURATED_FAT),
    _22_4_N6(MU.GRAM, POLYUNSATURATED_FAT),
    _22_5_N3(MU.GRAM, POLYUNSATURATED_FAT),
    _22_6_N3(MU.GRAM, POLYUNSATURATED_FAT),

    // TRANS
    FA_TRANS(MU.GRAM, TOTAL_FAT),
    FA_TRANS_MONOENOIC(MU.GRAM, TOTAL_FAT),
    FA_TRANS_POLYENOIC(MU.GRAM, TOTAL_FAT),

    // PROTEINA
    PROTEIN(MU.GRAM, GeneralNutrientGroup.PROTEIN_AND_AMINO_ACIDS),
    TRYPTOPHAN(MU.GRAM, PROTEIN),
    THREONINE(MU.GRAM, PROTEIN),
    ISOLEUCINE(MU.GRAM, PROTEIN),
    LEUCINE(MU.GRAM, PROTEIN),
    LYSINE(MU.GRAM, PROTEIN),
    METHIONINE(MU.GRAM, PROTEIN),
    CYSTINE(MU.GRAM, PROTEIN),
    PHENYLALANINE(MU.GRAM, PROTEIN),
    TYROSINE(MU.GRAM, PROTEIN),
    VALINE(MU.GRAM, PROTEIN),
    ARGININE(MU.GRAM, PROTEIN),
    HISTIDINE(MU.GRAM, PROTEIN),
    ALANINE(MU.GRAM, PROTEIN),
    ASPARTIC_ACID(MU.GRAM, PROTEIN),
    GLUTAMIC_ACID(MU.GRAM, PROTEIN),
    CLYCINE(MU.GRAM, PROTEIN),
    PROLINE(MU.GRAM, PROTEIN),
    SERINE(MU.GRAM, PROTEIN),
    HYDROXYPROLINE(MU.GRAM, PROTEIN),

    // VITAMINAS
    // VITAMINA A
    VITAMIN_A_IU(MU.IU, GeneralNutrientGroup.VITAMINS),
    RETINOL(MU.MICROGRAM, VITAMIN_A_IU),
    VITAMIN_A_RAE(MU.MICROGRAM, VITAMIN_A_IU),
    CAROTENE_ALPHA(MU.MICROGRAM, VITAMIN_A_IU),
    CAROTENE_BETA(MU.MICROGRAM, VITAMIN_A_IU),
    CRYPTOXANTHIN(MU.MICROGRAM, VITAMIN_A_IU),
    LYCOPENE(MU.MICROGRAM, VITAMIN_A_IU),
    LUTEIN_ZEAXANTHIN(MU.MICROGRAM, VITAMIN_A_IU),

    // VITAMINA B
    THIAMIN(MU.MILLIGRAM, GeneralNutrientGroup.VITAMINS),
    RIBOFLAVIN(MU.MILLIGRAM, GeneralNutrientGroup.VITAMINS),
    NIACIN(MU.MILLIGRAM, GeneralNutrientGroup.VITAMINS),
    PANTOTHENIC_ACID(MU.MILLIGRAM, GeneralNutrientGroup.VITAMINS),
    VITAMIN_B6(MU.MILLIGRAM, GeneralNutrientGroup.VITAMINS),
    FOLATE(MU.MICROGRAM, GeneralNutrientGroup.VITAMINS),
    FOLIC_ACID(MU.MICROGRAM, FOLATE),
    FOLATE_FOOD(MU.MICROGRAM, FOLATE),
    FOLATE_DFE(MU.MICROGRAM, FOLATE),
    VITAMIN_B12(MU.MICROGRAM, GeneralNutrientGroup.VITAMINS),
    CHOLINE(MU.MILLIGRAM, GeneralNutrientGroup.VITAMINS),
    VITAMIN_B12_ADDED(MU.MICROGRAM, GeneralNutrientGroup.VITAMINS),

    // VITAMINA C
    VITAMIN_C(MU.MILLIGRAM, GeneralNutrientGroup.VITAMINS),

    // VITAMINA D
    VITAMIN_D_IU(MU.IU, GeneralNutrientGroup.VITAMINS),
    VITAMIN_D2(MU.MICROGRAM, VITAMIN_D_IU),
    VITAMIN_D3(MU.MICROGRAM, VITAMIN_D_IU),
    VITAMIN_D_D2_D3(MU.MICROGRAM, VITAMIN_D_IU),

    // VITAMINA E
    VITAMIN_E(MU.MILLIGRAM, GeneralNutrientGroup.VITAMINS),
    TOCOPHEROL_BETA(MU.MILLIGRAM, VITAMIN_E),
    TOCOPHEROL_GAMMA(MU.MILLIGRAM, VITAMIN_E),
    TOCOPHEROL_DELTA(MU.MILLIGRAM, VITAMIN_E),
    TOCOTRIENOL_ALPHA(MU.MILLIGRAM, VITAMIN_E),
    TOCOTRIENOL_BETA(MU.MILLIGRAM, VITAMIN_E),
    TOCOTRIENOL_GAMMA(MU.MILLIGRAM, VITAMIN_E),
    TOCOTRIENOL_DELTA(MU.MILLIGRAM, VITAMIN_E),
    VITAMIN_E_ADDED(MU.MILLIGRAM, VITAMIN_E),

    // VITAMINA K
    VITAMIN_K(MU.MICROGRAM, GeneralNutrientGroup.VITAMINS),
    DIHYDROPHYLLOQUINONE(MU.MICROGRAM, VITAMIN_K),
    VITAMINE_K2(MU.MICROGRAM, VITAMIN_K),

    BETAINE(MU.MILLIGRAM, GeneralNutrientGroup.VITAMINS),

    // MINERALES
    CALCIUM(MU.MILLIGRAM, GeneralNutrientGroup.MINERALS),
    IRON(MU.MILLIGRAM, GeneralNutrientGroup.MINERALS),
    MAGNESIUM(MU.MILLIGRAM, GeneralNutrientGroup.MINERALS),
    PHOSPHORUS(MU.MILLIGRAM, GeneralNutrientGroup.MINERALS),
    POTASSIUM(MU.MILLIGRAM, GeneralNutrientGroup.MINERALS),
    SODIUM(MU.MILLIGRAM, GeneralNutrientGroup.MINERALS),
    ZINC(MU.MILLIGRAM, GeneralNutrientGroup.MINERALS),
    COOPER(MU.MILLIGRAM, GeneralNutrientGroup.MINERALS),
    FLUORIDE(MU.MICROGRAM, GeneralNutrientGroup.MINERALS),
    MANGANESE(MU.MILLIGRAM, GeneralNutrientGroup.MINERALS),
    SELENIUM(MU.MICROGRAM, GeneralNutrientGroup.MINERALS),

    // STEROLS
    CHOLESTEROL(MU.MILLIGRAM, GeneralNutrientGroup.STEROLS),
    PHYTOSTEROLS(MU.MILLIGRAM, GeneralNutrientGroup.STEROLS),
    STIGMASTEROL(MU.MILLIGRAM, PHYTOSTEROLS),
    CAMPESTEROL(MU.MILLIGRAM, PHYTOSTEROLS),
    BETA_SITOSTEROL(MU.MILLIGRAM, PHYTOSTEROLS),

    // OTROS
    ASH(MU.GRAM, GeneralNutrientGroup.OTHERS),
    ALCOHOL(MU.GRAM, GeneralNutrientGroup.OTHERS),
    WATER(MU.GRAM, GeneralNutrientGroup.OTHERS),
    CAFFEINE(MU.MILLIGRAM, GeneralNutrientGroup.OTHERS),
    THEOBROMINE(MU.MILLIGRAM, GeneralNutrientGroup.OTHERS);


    private final Unit unit;
    private final NutrientGroup nutrientGroup;

    private Nutrient(Unit unit, NutrientGroup nutrientsGroup) {
        this.unit = unit;
        this.nutrientGroup = nutrientsGroup;
    }

    public Unit getUnit() {
        return unit;
    }

    public NutrientGroup getNutrientGroup() {
        return nutrientGroup;
    }

    @Override
    public List<Nutrient> getNutrients() {
        List<Nutrient> nutrientList = new ArrayList<>();
        for (Nutrient nutrient : Nutrient.values())
            if (nutrient.getNutrientGroup().equals(this))
                nutrientList.add(nutrient);

        return nutrientList;
    }
}
